### ISSUE TITLE
[Bug] Fix Cart Buttons for smaller devices

### ISSUE THREAD

**Issue by suryanshsingh2001** [suryanshsingh2001/MyLibrary#14]
## Issue: Weird Size of Call to Action Buttons on Smaller Devices

**Description:**

The call to action buttons on the cart page are displaying with irregular sizes when viewed on smaller devices. This issue affects the user experience and needs to be addressed to ensure consistency and usability.

**Steps to Reproduce:**

1. Open the MyLibrary application on a smaller device or resize the browser window to a smaller viewport.

2. Navigate to the cart page.

3. Observe the size of the call to action buttons (e.g., "Checkout," "Continue Shopping").

**Expected Behavior:**

The call to action buttons on the cart page should have a consistent and visually appealing size on all devices, providing an intuitive user experience.

**Actual Behavior:**

The call to action buttons appear with irregular sizes on smaller devices, which may lead to a suboptimal user interface.

**Screenshots:**

![image](https://github.com/suryanshsingh2001/MyLibrary/assets/80690023/65b73d93-8bd1-40ac-a741-171187eaa7eb)

This issue is crucial for ensuring a responsive and user-friendly design, especially for users accessing MyLibrary on smaller devices. Your assistance in addressing this problem is highly appreciated!

**Note:**

Please feel free to assign this issue to yourself if you are interested in working on it, or leave a comment if you have additional insights or suggestions for its resolution.

**Comment by gaurab-khanal** [comment]
Can I work on this issue?

**Comment by suryanshsingh2001** [comment]
@gaurab-khanal Sure, I have assigned you this issue,. You can start working on right away. Happy Coding 🧑‍💻

**Comment by gaurab-khanal** [comment]
@suryanshsingh2001  Project is running fine but I couldn't get books content even after adding respective API keys in .env file. As well login isnt working? WHat can i do?

**Comment by suryanshsingh2001** [comment]
Share your booklist.jsx code.

**Comment by suryanshsingh2001** [comment]
@gaurab-khanal Could share the code for Booklist.jsx. Also, Please check the code of booklist against Booklist-old.jsx in this gist
https://gist.github.com/suryanshsingh2001/f89973b3f3d826b60f6426796a5063f7

**Comment by suryanshsingh2001** [comment]
@gaurab-khanal Hey, I have made some changes in these components to allow cart functionality without authentication. Make sure to fetch the new changes and start working on it.

**Comment by suryanshsingh2001** [comment]
New Issue #17
