### ISSUE TITLE
Add a custom CSS scrollbar for better aesthetics

### ISSUE THREAD

**Issue by Arbtrage** [suryanshsingh2001/MyLibrary#22]
**Is your feature request related to a problem? Please describe.**
The website looks aesthetically pleasing but the scrollbar is of the basic browser version.
<img width="436" alt="image" src="https://github.com/suryanshsingh2001/MyLibrary/assets/100552235/3b472c5f-5d9f-416d-83f6-da4cc9c587b6">

**Describe the solution you'd like**
Would like to add a custom scrollbar according to the color pallete of the overall website.

Would like to work on this issue , please assign me this @suryanshsingh2001

**Comment by suryanshsingh2001** [comment]
@Arbtrage Good addition. I have assigned you the issue. You can start working on it. Happy Coding 🧑‍💻

**Comment by Arbtrage** [comment]
Hey @suryanshsingh2001 , does this look good ?
<img width="960" alt="image" src="https://github.com/suryanshsingh2001/MyLibrary/assets/100552235/a1aa6115-6fe5-4e62-aa87-e73df9fcc308">

**Comment by suryanshsingh2001** [comment]
This looks good 👍. You can make a PR for this.
