### ISSUE TITLE
Uneven positioning of arrow keys

### ISSUE THREAD

**Issue by Arbtrage** [suryanshsingh2001/MyLibrary#24]
**Describe the bug**
The keys are not positioned in the correct way. It looks messy.

**Screenshots**
<img width="286" alt="image" src="https://github.com/suryanshsingh2001/MyLibrary/assets/100552235/53e49452-9fa6-4e1d-b298-3ee19a0fb137">

Would like to work on this. Please assign me this issue @suryanshsingh2001 .

**Comment by suryanshsingh2001** [comment]
@Arbtrage Assigned the issue. You can start working on it. Happy Coding 🧑‍💻

**Comment by Arbtrage** [comment]
Hey @suryanshsingh2001 just a suggestion , woudn't it look better this way in it's default settings instead of having an up-down arrow key ?
<img width="332" alt="image" src="https://github.com/suryanshsingh2001/MyLibrary/assets/100552235/0b800b58-73ec-4a61-8737-c6cd3a9cd93b">

**Comment by suryanshsingh2001** [comment]
Yeah this looks better @Arbtrage .

**Comment by Arbtrage** [comment]
Cool , creating a PR for the same.
