### ISSUE TITLE
Search bar UI Improvement

### ISSUE THREAD

**Issue by Arbtrage** [suryanshsingh2001/MyLibrary#28]
**Is your feature request related to a problem? Please describe.**
The search bar is very basic. 
<img width="371" alt="image" src="https://github.com/suryanshsingh2001/MyLibrary/assets/100552235/32e9dc30-319f-418e-8f57-4ceb39151421">

**Describe the solution you'd like**
Would like to provide a better ui for the search bar.

Please assign me this issue @suryanshsingh2001 .

**Comment by suryanshsingh2001** [comment]
@Arbtrage I have assigned the issue to you. Happy Coding 🧑‍💻
