### ISSUE TITLE
IMPROVING NAVBAR UI

### ISSUE THREAD

**Issue by Ayusht777** [suryanshsingh2001/MyLibrary#33]
the website Navbar is  to scaled for ui perspective . so can i improve it and some minors ui improvement

**Comment by suryanshsingh2001** [comment]
@Ayusht777  Sure, assigned the issue, you can start working on it.

**Comment by Ayusht777** [comment]
hey can i use react icons library in it , also can i change the logo of this website

**Comment by suryanshsingh2001** [comment]
> hey can i use react icons library in it , also can i change the logo of this website

Sure, you can use react-icons and change logo if needed. Do share the screenshot of the new navbar.

**Comment by Ayusht777** [comment]
hey this new improve navbar and if you want improve something in it than tell me 
![Screenshot (269)](https://github.com/suryanshsingh2001/MyLibrary/assets/106388215/f461d9ec-d057-4569-abe8-c9e56f1a657e)

**Comment by Ayusht777** [comment]
hi i am getting this error creating the pull request 
Someone is attempting to deploy a commit to a Personal Account owned by @suryanshsingh2001 on [Vercel](https://vercel.com/).

@suryanshsingh2001 first needs to [authorize it](https://vercel.com/git/authorize?type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%224ffd4b7368c7b6af193e0923dc50865d12b2e87b%22%7D%2C%22id%22%3A%22QmXeUqWgmxpFuKdTFuEaccpwgoibk7cK2TRge7d94UMqBA%22%2C%22org%22%3A%22suryanshsingh2001%22%2C%22prId%22%3A43%2C%22repo%22%3A%22MyLibrary%22%7D).
