### ISSUE TITLE
Improve Search Bar

### ISSUE THREAD

**Issue by MokshagnaV** [suryanshsingh2001/MyLibrary#34]
**Is your feature request related to a problem? Please describe.**
Current Search element floods all the search result into page, which pushes the below elements down and it leads to UI inconvenience.
![Screenshot from 2023-10-15 19-01-20](https://github.com/suryanshsingh2001/MyLibrary/assets/92448513/552b160a-c049-4482-a9a3-cad3e4beab14)

**Describe the solution you'd like**
Make use of Select elements like Async Autocomplete or React-select
![image](https://github.com/suryanshsingh2001/MyLibrary/assets/92448513/45942776-3d32-4980-9ff1-e8a6b468b40e)
It looks like this. Searches are loads the search results as a options.

**Describe alternatives you've considered**

**Additional context**
Add i will improve the filter and sortby element UI

**Comment by suryanshsingh2001** [comment]
@MokshagnaV  Sure, I have assigned you the issue you can start working on it

**Comment by MokshagnaV** [comment]
Hey :wave:
 
I finish implementing it. Have a look on it
![Search preview](https://github.com/suryanshsingh2001/MyLibrary/assets/92448513/14edef8e-a967-4d08-b4d3-99555c3ff759)

Displays Toasty on error
![image](https://github.com/suryanshsingh2001/MyLibrary/assets/92448513/dbe3e1f7-42c4-4805-aa29-ee8d06d2bb87)

If it is okay I will open a PR

Will i leave the previous implement as comments or delete those line, if everything is working fine without those lines?

And Please, add this as Hacktoberfest

**Comment by suryanshsingh2001** [comment]
This looks good, you can submit a PR. @MokshagnaV

**Comment by suryanshsingh2001** [comment]
> Hey 👋
> 
> I finish implementing it. Have a look on it ![Search preview](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) [ ![Search preview](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) ](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) [ ](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif)
> 
> Displays Toasty on error ![image](https://user-images.githubusercontent.com/92448513/275335127-dbe3e1f7-42c4-4805-aa29-ee8d06d2bb87.png)
> 
> If it is okay I will open a PR
> 
> Will i leave the previous implement as comments or delete those line, if everything is working fine without those lines?
> 
> And Please, add this as Hacktoberfest

No need to comment it, Make sure everything works at your end and change it.

**Comment by MokshagnaV** [comment]
> > Hey 👋
> > 
> > I finish implementing it. Have a look on it ![Search preview](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) [ ![Search preview](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) ](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) [ ](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif)
> > 
> > Displays Toasty on error ![image](https://user-images.githubusercontent.com/92448513/275335127-dbe3e1f7-42c4-4805-aa29-ee8d06d2bb87.png)
> > 
> > If it is okay I will open a PR
> > 
> > Will i leave the previous implement as comments or delete those line, if everything is working fine without those lines?
> > 
> > And Please, add this as Hacktoberfest
> 
> No need to comment it, Make sure everything works at your end and change it.


Sorry, I opened a PR with those comments. I am sure that comments can be removed

**Comment by MokshagnaV** [comment]
> > > Hey 👋
> > > 
> > > I finish implementing it. Have a look on it ![Search preview](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) [ ![Search preview](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) ](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif) [ ](https://user-images.githubusercontent.com/92448513/275333870-14edef8e-a967-4d08-b4d3-99555c3ff759.gif)
> > > 
> > > Displays Toasty on error ![image](https://user-images.githubusercontent.com/92448513/275335127-dbe3e1f7-42c4-4805-aa29-ee8d06d2bb87.png)
> > > 
> > > If it is okay I will open a PR
> > > 
> > > Will i leave the previous implement as comments or delete those line, if everything is working fine without those lines?
> > > 
> > > And Please, add this as Hacktoberfest
> > 
> > No need to comment it, Make sure everything works at your end and change it.
> 
> 
> Sorry, I opened a PR with those comments. I am sure that comments can be removed. Everything will be fine.

Can I do that again and raise a PR?
