### ISSUE TITLE
Wrong usage of class HTML attribute

### ISSUE THREAD

**Issue by marchintosh94** [suryanshsingh2001/MyLibrary#50]
**Describe the bug**
I noticed that in the Footer.jsx component instead of using `className` attribute, is been used the attribute `class`

**To Reproduce**
1. Go to file client/src/Components/Footer.jsx
2. See errors starting from line ~18 to ~30

**Expected behavior**
The `class` attribute have to be replaced with `className` and the error in the console should gone.

**Screenshots**
![image](https://github.com/user-attachments/assets/81aaf50f-8085-450e-b1be-24c5bd5c14e3)
![image](https://github.com/user-attachments/assets/2f0f8abb-ac95-4c49-be3d-da55b7d0c425)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by marchintosh94** [comment]
@suryanshsingh2001 I'd like to take this issue

**Comment by suryanshsingh2001** [comment]
@marchintosh94  Sure, I have assigned you the issue!
