### ISSUE TITLE
increment or decrement quantity

### ISSUE THREAD

**Issue by kanikaa-3018** [suryanshsingh2001/MyLibrary#53]
for adding or removing quantity of a particular book, as well as price must also be visible .pls assign me this issue for hacktoberfest24

**Comment by suryanshsingh2001** [comment]
Hey @kanikaa-3018 

### 📝 Explaining the Issue Further

If you need more context on the issue you're working on, feel free to reach out! Here’s a bit more detail to help guide you:

- **Issue Summary:** Briefly explain the problem or goal of the task.
- **Key Points:** Highlight any important details or specific areas of focus.
- **Resources:** Mention any useful documentation or related PRs.

Please don’t hesitate to ask questions or request clarification if anything is unclear! We're here to help you succeed.

**Comment by suryanshsingh2001** [comment]
Closing issue due to stale
