### ISSUE TITLE
[Bug] Fixing the position of "Add to Cart" button

### ISSUE THREAD

**Issue by dcode-github** [suryanshsingh2001/MyLibrary#58]
**Is your feature request related to a problem? Please describe.**
So, currently the **Add to Cart** button is not consistent in position and depends on the length of the details of the book, which give a bad user experience.

**Describe the solution you'd like**
Fixed the **Add to Cart** button at the bottom right position

**Describe alternatives you've considered**

**Comparison**
Current-
![image](https://github.com/user-attachments/assets/7cd6a762-0d1f-47c4-9dc9-67d0fe273ccb)
Proposed-
![image](https://github.com/user-attachments/assets/07205a9d-26a0-42d4-a229-3a4479701dbb)

I would like you to assign this to me under **Hacktoberfest** tag

**Comment by suryanshsingh2001** [comment]
@dcode-github Hey, please feel free to proceed with fixing the issue.
