### ISSUE TITLE
[Bug] Books list not getting sorted on changing the applying Sort By feature

### ISSUE THREAD

**Issue by dcode-github** [suryanshsingh2001/MyLibrary#61]
**Describe the bug**
The list is not getting sorted when applying sorting according to relevance or newest or oldest.

I'll be happy to take on this issue and solve it.
Please assign this to me.

**Comment by Arystar01** [comment]
Hi 
I want to work on this issue @suryanshsingh2001 
Kindly assign me.

**Comment by suryanshsingh2001** [comment]
> Hi I want to work on this issue @suryanshsingh2001 Kindly assign me.

Hey @Arystar01, This is issue is almost finished by @dcode-github in #62 
Please feel free to have a look at other issues or create your own.
