### ISSUE TITLE
Add a review or Rating Star in every card

### ISSUE THREAD

**Issue by Naren456** [suryanshsingh2001/MyLibrary#70]
![image](https://github.com/user-attachments/assets/ea54241f-5afe-4519-9754-cb283b42b372)
Sir ,I want to add review star  feature in your project site 

It shows the product popularity  and user feedback about that product.
It give clear understanding to the customer.
Important :Shapes/Images are more attractive than text
If you would like to add this feature 
please assign me .

**Comment by suryanshsingh2001** [comment]
@Naren456 Hey, this is a good issue. To move forward with this please have a look at Google Books API for fetching reviews of a book. Let me know what you find.

**Comment by Naren456** [comment]
I haven't started yet.
Please assign to someone else
As I 'm unable to do it.
